[platformio]
src_dir = src
include_dir = include

[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200

board_build.partitions = huge_app.csv

build_flags =
  -D CLASSPOD_GATEWAY_FIRMWARE
  -D BOARD_HAS_PSRAM

lib_deps =
  bblanchon/ArduinoJson@^7.1.0
