[platformio]
src_dir = src
include_dir = include

[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200

board_build.partitions = huge_app.csv

build_flags =
  -D CLASSPOD_GATEWAY_FIRMWARE
  -D BOARD_HAS_PSRAM
  -D API_HOST=\"13.211.174.183\"
  -D API_PORT=80
  -D GATEWAY_SECRET=\"local-dev-secret-key\"
  -D GATEWAY_ID=\"esp32-cam-node-1\"

lib_deps =
  bblanchon/ArduinoJson@^7.1.0
